# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The log probability mass function of the Poisson distribution.
#' 
#' @param x An integer.
#' @param lambda A positive scalar.
#' @return A log-probability.
#' @export
#' @keywords internal
poisson_lpmf <- function(x, lambda) {
    .Call('scanstatistics_poisson_lpmf', PACKAGE = 'scanstatistics', x, lambda)
}

#' Terms in the log-product (sum) of the EB-ZIP window statistic.
#' 
#' Computes one or more terms in the log-product (sum) of the numerator or 
#' denominator of the EB-ZIP window statistic (i.e. the one calculated for a 
#' given space-time window W).
#' @param p Numeric vector of structural zero probabilities.
#' @param d Numeric vector of estimates of the structural zero indicators. Of 
#'    same length as \code{p}.
#' @param mu Numeric vector of given/estimated Poisson expected value 
#' parameters. Of same length as \code{p}.
#' @param y Integer vector of observed counts. Of same length as \code{p}.
#' @param tol Scalar; probability p below this is considered equal to zero.
#' @return A numeric vector of same length as input vector \code{p}.
#' @keywords internal
zip_statistic_logfactor <- function(p, d, mu, y, tol = 1e-08) {
    .Call('scanstatistics_zip_statistic_logfactor', PACKAGE = 'scanstatistics', p, d, mu, y, tol)
}

#' Estimate the relative risk for an outbreak using a ZIP distribution.
#' 
#' Scalar estimate of the relative risk \eqn{q} for zero-inflated Poisson data.
#' @param d A vector of indicator variables for whether the corresponding count
#'    in the argument \code{y} is an excess zero or not. Can also be estimates 
#'    of these indicators.
#' @param mu A vector of given/estimated Poisson expected value parameters, of 
#'    same length as \code{d}.
#' @param y An integer vector of the observed counts, of same length as 
#'    \code{d}.
#' @return A scalar, the estimated relative risk.
#' @keywords internal
estimate_zip_relrisk <- function(d, mu, y) {
    .Call('scanstatistics_estimate_zip_relrisk', PACKAGE = 'scanstatistics', d, mu, y)
}

#' Estimate the indicators of excess zeros for a ZIP distribution.
#' 
#' Given counts and (estimated) Poisson expected value parameters and excess 
#' zero probabilities, this function estimates the indicator variable for an 
#' excess zero, for each count.
#' @param p A numeric vector, each element being the given/estimated 
#'    probability of an excess zero for the corresponding count in \code{y}.
#' @param mu A numeric vector, each element being the given/estimated Poisson 
#'    expected value parameter for the corresponding count in \code{y}. Of same 
#'    length as \code{p}.
#' @param y An integer vector containing the observed counts. Of same length as 
#'    \code{p}.
#' @return A numeric vector, of same length as the input vector \code{p}.
#' @keywords internal
estimate_d <- function(p, mu, y) {
    .Call('scanstatistics_estimate_d', PACKAGE = 'scanstatistics', p, mu, y)
}

#' Estimates the ZIP relative risk and excess zero indicators for a window.
#' 
#' For a single spatial or space-time window, this function uses the EM 
#' algorithm to estimate the relative risk and the excess zero indicators for 
#' counts assumed to be generated from a zero-inflated Poisson distribution.
#' @param p A numeric vector of the given/estimated excess zero probabilities 
#'    corresponding to each count.
#' @param mu A numeric vector of the given/estimated Poisson expected value
#'    parameters corresponding to each count. Of same length as \code{p}.
#' @param y An integer vector of the observed counts, of same length as 
#'    \code{p}.
#' @param tol A scalar between 0 and 1. It is the absolute tolerance criterion
#'    for the estimate of the excess zero indicator; convergence is reached when
#'    two successive elements in the sequence of estimates have an absolute 
#'    difference less than \code{tol}.
#' @return A list with two elements:
#' \describe{
#'   \item{q}{Scalar estimate of the relative risk.}
#'   \item{dstar}{Estimates of the excess zero indicator variables.}
#' }
#' @keywords internal
zip_em_estimates <- function(p, mu, y, tol = 0.01) {
    .Call('scanstatistics_zip_em_estimates', PACKAGE = 'scanstatistics', p, mu, y, tol)
}

#' Calculate a term in the sum of the logarithm of the ZIP window statistic.
#' 
#' This function calculates a term which appears in the sum of the logarithm of
#' the zero-inflated Poisson statistic for a given space-time window.
#' @param q Scalar; the relative risk.
#' @param p Numeric vector of excess zero probabilities.
#' @param dstar Numeric vector of estimates of the excess zero indicators, under 
#'    the alternative hypothesis of an outbreak. Of same length as \code{p}.
#' @param ddagger Numeric vector of estimates of the excess zero indicators, 
#'    under the null hypothesis of no outbreak. Of same length as \code{p}.
#' @param mu Numeric vector of given/estimated Poisson expected value 
#'    parameters. Of same length as \code{p}.
#' @param y Integer vector of observed counts. Of same length as \code{p}.
#' @return A numeric vector of same length as input vector \code{p}.
#' @keywords internal
zip_statistic_term <- function(q, p, dstar, ddagger, mu, y) {
    .Call('scanstatistics_zip_statistic_term', PACKAGE = 'scanstatistics', q, p, dstar, ddagger, mu, y)
}

#' Calculate the ZIP statistic for a single space-time window.
#' 
#' Calculate the single-window statistic for the zero-inflated Poisson 
#' distribution using the EM algorithm.
#' @inheritParams zip_em_estimates
#' @param ... Named parameters passed to \code{\link{zip_em_estimates}}.
#' @return A scalar, the (logarithm of the) ZIP statistic.
#' @keywords internal
window_zip_statistic <- function(p, mu, y, tol = 0.01) {
    .Call('scanstatistics_window_zip_statistic', PACKAGE = 'scanstatistics', p, mu, y, tol)
}

#' Calculate the ZIP window statistic over all durations, for a given zone.
#' 
#' This function calculates the zero-inflated Poisson statistic for a given 
#' spatial zone, for all durations considered.
#' @param duration An integer vector.
#' @inheritParams zip_em_estimates
#' @return A list with two elements:
#' \describe{
#'   \item{duration}{Vector of integers from 1 to \code{maxdur}.}
#'   \item{statistic}{Numeric vector containing the ZIP statistics corresponding
#'   to each duration, for the given spatial zone.}
#' }
#' @keywords internal
calc_zipstat_over_duration <- function(duration, p, mu, y, maxdur, tol = 0.01) {
    .Call('scanstatistics_calc_zipstat_over_duration', PACKAGE = 'scanstatistics', duration, p, mu, y, maxdur, tol)
}

