# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The log probability mass function of the Poisson distribution.
#' 
#' The log probability mass function of the Poisson distribution, evaluated at
#' \code{y}.
#' @param y An integer.
#' @param mu A positive scalar.
#' @return A log-probability.
#' @export
#' @keywords internal
poisson_lpmf <- function(y, mu) {
    .Call('scanstatistics_poisson_lpmf', PACKAGE = 'scanstatistics', y, mu)
}

#' Calculate the Poisson log-likelihood.
#'
#' Calculate the log-likelihood for the Poisson distribution.
#' @param y A non-negative integer vector; the observed counts.
#' @param mu A vector of positive scalars; the expected values of the counts.
#' @param q A scalar greater than or equal to 1; the relative risk.
#' @return A non-positive scalar; the log-likelihood.
#' @keywords internal
poisson_loglihood <- function(y, mu, q) {
    .Call('scanstatistics_poisson_loglihood', PACKAGE = 'scanstatistics', y, mu, q)
}

#' The log probability mass function of the ZIP distribution.
#' 
#' The log probability mass function of the Poisson distribution, evaluated at
#' \code{x}.
#' @param y A non-negative integer; the observed count.
#' @param mu A positive scalar; the expected value of the count.
#' @param p A scalar between 0 and 1; the structural zero probability.
#' @return A non-positive scalar; the loglihood contribution of the 
#'    observation.
#' @keywords internal
zip_lpmf <- function(y, mu, p) {
    .Call('scanstatistics_zip_lpmf', PACKAGE = 'scanstatistics', y, mu, p)
}

#' Calculate the ZIP log-likelihood.
#'
#' Calculate the (incomplete information) log-likelihood for the zero-inflated 
#' Poisson distribution.
#' @param y A vector of non-negative integers; the observed counts.
#' @param mu A vector of positive scalars; the expected values of the counts.
#' @param p A vector of scalars between 0 and 1; the structural zero
#'    probabilities.
#' @param q A scalar greater than or equal to 1; the relative risk.
#' @return A non-positive scalar; the incomplete information ZIP loglihood.
#' @keywords internal
zip_loglihood <- function(y, mu, p, q) {
    .Call('scanstatistics_zip_loglihood', PACKAGE = 'scanstatistics', y, mu, p, q)
}

#' Calculate the Poisson loglihood ratio statistic for each zone and duration.
#'
#' Calculate the Poisson loglihood ratio statistic for each zone and duration. 
#' The estimate of the relative risk is also calculated and returned.
#' @param counts A matrix of non-negative integers; the observed counts. Rows
#'    indicate time, ordered from most recent (row 1) to least recent. Columns
#'    indicate locations; the locations are numbered from 1 and up.
#' @param baselines A matrix of positive scalars; the expected values of the
#'    counts. Of the same dimensions as \code{counts}.
#' @param zones An integer vector containing the zones, stored one after
#'    another. Each zone is found using the elements of the parameter
#'    \code{zone_lengths}. For example, if the first element of
#'    \code{zone_lengths} is 5, then the first 5 elements of \code{zones}
#'    make up the first zone. If the second element of \code{zone_lengths} is
#'    2, then elements 6 and 7 of \code{zones} make up the second zone, and so
#'    on. Note that the zones are numbered from 0 and up in the input, but
#'    from 1 and up in the output.
#' @param zone_lengths An integer vector holding the number of locations in
#'    each zone.
#' @param rel_tol A positive scalar. If the relative change in the incomplete
#'    information likelihood is less than this value, then the EM algorithm is
#'    deemed to have converged.
#' @return A data frame with five columns:
#'    \describe{
#'      \item{zone}{The (number of the) zone.}
#'      \item{duration}{The duration.}
#'      \item{score}{The value of the loglihood ratio statistic.}
#'      \item{relrisk}{The estimated relative risk.}
#'    }
#' @keywords internal
calc_all_poisson_eb <- function(counts, agg_baselines, zones, zone_lengths) {
    .Call('scanstatistics_calc_all_poisson_eb', PACKAGE = 'scanstatistics', counts, agg_baselines, zones, zone_lengths)
}

#' Calculate the conditional expectation of the structural zero indicator.
#' 
#' Calculate the conditional expectation of the structural zero indicator for 
#' the zero-inflated Poisson distribution.
#' @param mu The expected values of the count (which is zero).
#' @param p The structural zero probability.
#' @param q A scalar greater than or equal to 1; the relative risk.
#' @return A scalar between 0 and 1.
#' @keywords internal
est_zip_zero_indicator <- function(mu, p, q) {
    .Call('scanstatistics_est_zip_zero_indicator', PACKAGE = 'scanstatistics', mu, p, q)
}

#' Estimate the relative risk for the ZIP distribution.
#' 
#' Estimate the relative risk for the ZIP distribution.
#' @param y_sum A non-negative integer; the sum of the observed counts.
#' @param mu A vector of positive scalars; the expected values of the counts.
#' @param p A vector of scalars between 0 and 1; the structural zero
#'    probabilities.
#' @param d_hat A vector of estimates of the structural zero indicators.
#' @return A scalar; the relative risk.
#' @keywords internal
est_zip_relrisk <- function(y_sum, mu, p, d_hat) {
    .Call('scanstatistics_est_zip_relrisk', PACKAGE = 'scanstatistics', y_sum, mu, p, d_hat)
}

#' Calculate the ZIP loglihood ratio statistic and the relative risk.
#' @param y A non-negative integer vector; the observed counts.
#' @param mu A vector of positive scalars; the expected values of the counts.
#' @param p A vector of scalars between 0 and 1; the structural zero
#'    probabilities.
#' @param d_hat A vector of estimates of the structural zero indicators.
#' @param rel_tol The absolute convergence criterion.
#' @return A list with three elements:
#'    \enumerate{
#'      \item The loglihood ratio statistic.
#'      \item The estimated relative risk.
#'      \item The number of iterations of the EM algorithm performed.
#'    } 
#' @keywords internal
score_zip <- function(y, mu, p, rel_tol = 1e-2) {
    .Call('scanstatistics_score_zip', PACKAGE = 'scanstatistics', y, mu, p, rel_tol)
}

#' Calculate the ZIP loglihood ratio statistic for each zone and duration.
#' 
#' Calculate the ZIP loglihood ratio statistic for each zone and duration. The
#' estimate of the relative risk is also calculated, along with the number of
#' iterations the EM algorithm performed for each zone and duration.
#' @param counts A matrix of non-negative integers; the observed counts. Rows
#'    indicate time, ordered from most recent (row 1) to least recent. Columns
#'    indicate locations; the locations are numbered from 1 and up.
#' @param baselines A matrix of positive scalars; the expected values of the 
#'    counts. Of the same dimensions as \code{counts}.
#' @param probs A matrix of scalars between 0 and 1; the structural zero
#'    probabilities. Of the same dimensions as \code{counts}.
#' @param zones An integer vector containing the zones, stored one after 
#'    another. Each zone is found using the elements of the parameter 
#'    \code{zone_lengths}. For example, if the first element of 
#'    \code{zone_lengths} is 5, then the first 5 elements of \code{zones}
#'    make up the first zone. If the second element of \code{zone_lengths} is
#'    2, then elements 6 and 7 of \code{zones} make up the second zone, and so
#'    on. Note that the zones are numbered from 0 and up in the input, but
#'    from 1 and up in the output.
#' @param zone_lengths An integer vector holding the number of locations in 
#'    each zone.
#' @param rel_tol A positive scalar. If the relative change in the incomplete
#'    information likelihood is less than this value, then the EM algorithm is
#'    deemed to have converged.
#' @return A data frame with five columns:
#'    \describe{
#'      \item{zone}{The (number of the) zone.}
#'      \item{duration}{The duration.}
#'      \item{score}{The value of the loglihood ratio statistic.}
#'      \item{relrisk}{The estimated relative risk.}
#'      \item{n_iter}{The number of iterations performed by the EM algorithm.}
#'    } 
#' @keywords internal
calc_all_zip_eb <- function(counts, baselines, probs, zones, zone_lengths, rel_tol = 1e-2) {
    .Call('scanstatistics_calc_all_zip_eb', PACKAGE = 'scanstatistics', counts, baselines, probs, zones, zone_lengths, rel_tol)
}

#' Calculate the highest-value ZIP loglihood ratio statistic.
#' 
#' Calculate the ZIP loglihood ratio statistic for each zone and duration, but 
#' only keep the zone and duration with the highest value (the MLC). The 
#' estimate of the relative risk is also calculated, along with the number of 
#' iterations the EM algorithm performed.
#' @inheritParams calc_all_zip_eb
#' @return A data frame with five columns:
#'    \describe{
#'      \item{zone}{The top-scoring zone (spatial component of MLC).}
#'      \item{duration}{The corresponding duration (time-length of MLC).}
#'      \item{score}{The value of the loglihood ratio statistic (the scan
#'                   statistic).}
#'      \item{relrisk}{The estimated relative risk.}
#'      \item{n_iter}{The number of iterations performed by the EM algorithm.}
#'    } 
#' @keywords internal
calc_one_zip_eb <- function(counts, baselines, probs, zones, zone_lengths, rel_tol = 1e-2) {
    .Call('scanstatistics_calc_one_zip_eb', PACKAGE = 'scanstatistics', counts, baselines, probs, zones, zone_lengths, rel_tol)
}

